// Generated by text/template; DO NOT EDIT
package server

import (
	"encoding/json"
	"net/http"
	"strconv"
	"strings"
	"subLease/src/server/database"
	"subLease/src/server/domain"
	"subLease/src/server/socialSecurityNumber"

	"github.com/gorilla/mux"
)

func getOwnersHandler(database database.Database) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(database.GetOwners())
	}
}

func getOwnerHandler(database database.Database) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		id, _ := strconv.Atoi(mux.Vars(r)["id"])
		if owner, found := database.GetOwner(id); found {
			json.NewEncoder(w).Encode(owner)
		}
	}
}

func createOwnerHandler(database database.Database) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		var owner domain.Owner
		_ = json.NewDecoder(r.Body).Decode(&owner)

		json.NewEncoder(w).Encode(database.CreateOwner(owner))
	}
}

func updateOwnerHandler(db database.Database) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		var errors []string
		var id int

		queryValues := r.URL.Query()
		ownerUpdate := database.OwnerUpdate{}

		retrieveInt("id", queryValues, func(idString string) (int, error) {
			return strconv.Atoi(idString)
		}, &errors, func(parsedId int) {
			id = parsedId
		})

		retrieveString("firstName", queryValues, func(firstNameString string) (string, error) {
			return firstNameString, nil
		}, &errors, func(parsedFirstName string) {
			ownerUpdate.FirstName = &parsedFirstName
		})

		retrieveString("lastName", queryValues, func(lastNameString string) (string, error) {
			return lastNameString, nil
		}, &errors, func(parsedLastName string) {
			ownerUpdate.LastName = &parsedLastName
		})

		retrieveSocialSecurityNumber("socialSecurityNumber", queryValues, func(socialSecurityNumberString string) (socialSecurityNumber.SocialSecurityNumber, error) {
			var socialSecurityNumber socialSecurityNumber.SocialSecurityNumber
			err := json.NewDecoder(strings.NewReader(socialSecurityNumberString)).Decode(&socialSecurityNumber)
			return socialSecurityNumber, err
		}, &errors, func(parsedSocialSecurityNumber socialSecurityNumber.SocialSecurityNumber) {
			ownerUpdate.SocialSecurityNumber = &parsedSocialSecurityNumber
		})

		retrieveIntSlice("apartments", queryValues, func(apartmentsString string) ([]int, error) {
			var apartment []int
			err := json.NewDecoder(strings.NewReader(apartmentsString)).Decode(&apartment)
			return apartment, err
		}, &errors, func(parsedApartments []int) {
			ownerUpdate.Apartments = &parsedApartments
		})

		if len(errors) > 0 {
			jsonError, _ := json.Marshal(errors)
			w.Header().Set("Content-Type", "application/json")
			http.Error(w, string(jsonError), http.StatusBadRequest)
			return
		}

		updatedOwner, foundOwnerWithId := db.UpdateOwner(id, ownerUpdate)
		if foundOwnerWithId {
			json.NewEncoder(w).Encode(updatedOwner)
		} else {
			http.Error(w, "No owner with that id was found.", http.StatusBadRequest)
		}
	}
}

func deleteOwnerHandler(database database.Database) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		id, _ := strconv.Atoi(mux.Vars(r)["id"])
		if owner, found := database.DeleteOwner(id); found {
			json.NewEncoder(w).Encode(owner)
		}
	}
}
