// Generated by generate.go; do not edit manually
package database

import (
	"errors"
	"subLease/src/server/domain"
)

func (d actualDatabase) GetLeaseContracts() []domain.LeaseContract {
	return make([]domain.LeaseContract, 0, 0)
}

func (d actualDatabase) GetLeaseContract(id int) (domain.LeaseContract, bool) {
	return domain.LeaseContract{}, false
}

func (d actualDatabase) GetLeaseContractsById(ids []int) []domain.LeaseContract {
	return make([]domain.LeaseContract, 0, 0)
}

func (d actualDatabase) CreateLeaseContract(leaseContract domain.LeaseContract) int {
	return -1
}

func (d actualDatabase) UpdateLeaseContract(id int, leaseContractUpdate LeaseContractUpdate) (domain.LeaseContract, error) {
	return domain.LeaseContract{}, errors.New("not implemented")
}

func (d actualDatabase) DeleteLeaseContract(id int) (domain.LeaseContract, bool) {
	return domain.LeaseContract{}, false
}
