// Generated by generate.go; do not edit manually
package database

import (
	"errors"
	"subLease/src/server/domain"
	"subLease/src/server/socialSecurityNumber"
)

type OwnerUpdate struct {
	Id                   *int
	FirstName            *string
	LastName             *string
	SocialSecurityNumber *socialSecurityNumber.SocialSecurityNumber
	Apartments           *[]int
}

func (o *OwnerUpdate) UpdateOwnerWithValuesFrom(e domain.Owner, database Database) (domain.Owner, error) {
	if o.Id != nil {
		e.Id = *o.Id
	}
	if o.FirstName != nil {
		e.FirstName = *o.FirstName
	}
	if o.LastName != nil {
		e.LastName = *o.LastName
	}
	if o.SocialSecurityNumber != nil {
		e.SocialSecurityNumber = *o.SocialSecurityNumber
	}
	if o.Apartments != nil {

		e.Apartments = database.GetApartmentsById(*o.Apartments)
		if len(e.Apartments) != len(*o.Apartments) {
			return domain.Owner{}, errors.New("not all ids in o.Apartments found") // TODO: List the ids that weren't found
		}

	}
	return e, nil
}
