// Generated by generate.go; do not edit manually
package inMemoryDatabase

import (
	"errors"
	"subLease/src/server/database"
	"subLease/src/server/domain"
)

func (d InMemoryDatabase) GetLeaseContracts() []domain.LeaseContract {
	return d.leaseContracts
}

func (d InMemoryDatabase) GetLeaseContract(id int) (domain.LeaseContract, bool) {
	if leaseContract, found := findLeaseContractById(d.leaseContracts, id); found {
		return *leaseContract, found
	}
	return domain.LeaseContract{}, false
}

func (d InMemoryDatabase) GetLeaseContractsById(ids []int) []domain.LeaseContract {
	var foundLeaseContracts []domain.LeaseContract
	for _, id := range ids {
		if leaseContract, found := findLeaseContractById(d.leaseContracts, id); found {
			foundLeaseContracts = append(foundLeaseContracts, *leaseContract)
		}
	}
	return foundLeaseContracts
}

func findLeaseContractById(leaseContracts []domain.LeaseContract, id int) (*domain.LeaseContract, bool) {
	for _, leaseContract := range leaseContracts {
		if leaseContract.Id == id {
			return &leaseContract, true
		}
	}
	return nil, false
}

func (d *InMemoryDatabase) CreateLeaseContract(leaseContract domain.LeaseContract) int {
	d.leaseContractCounter++
	leaseContract.Id = d.leaseContractCounter
	d.leaseContracts = append(d.leaseContracts, leaseContract)
	return leaseContract.Id
}

func (d *InMemoryDatabase) UpdateLeaseContract(id int, leaseContractUpdate database.LeaseContractUpdate) (domain.LeaseContract, error) {
	entityToReturn := domain.LeaseContract{}
	var errorToReturn error
	if i := indexOfLeaseContract(d.leaseContracts, id); i != -1 {
		updated, err := leaseContractUpdate.UpdateLeaseContractWithValuesFrom(d.leaseContracts[i], d)
		if err != nil {
			errorToReturn = err
		} else {
			d.leaseContracts[i] = updated
			entityToReturn = updated
		}
	} else {
		errorToReturn = errors.New("no LeaseContract with that id was found")
	}
	return entityToReturn, errorToReturn
}

func indexOfLeaseContract(leaseContracts []domain.LeaseContract, id int) int {
	for i, leaseContract := range leaseContracts {
		if leaseContract.Id == id {
			return i
		}
	}
	return -1
}

func (d *InMemoryDatabase) DeleteLeaseContract(id int) (domain.LeaseContract, bool) {
	leaseContractToRemove := domain.LeaseContract{}
	found := false
	j := 0
	for _, leaseContract := range d.leaseContracts {
		if leaseContract.Id != id {
			d.leaseContracts[j] = leaseContract
			j++
		} else {
			leaseContractToRemove = leaseContract
			d.leaseContractCounter--
			found = true
		}
	}
	d.leaseContracts = d.leaseContracts[:j]
	return leaseContractToRemove, found
}
