// Generated by generate.go; do not edit manually
package domain

import "subLease/src/server/address"

type Apartment struct {
	Id      int
	Number  int
	Address address.Address
}

func CreateApartment(number int, address address.Address) Apartment {
	return Apartment{
		Number:  number,
		Address: address,
	}
}

func (a *Apartment) Equal(other *Apartment) bool {
	return a.Id == other.Id && a.Number == other.Number && a.Address.Equal(other.Address)
}
