// Generated by text/template; DO NOT EDIT
package domain




type Apartment struct {
    Id int
    Number int
    Address address.Address
}


func CreateApartment(number int, address address.Address) Apartment {
    return Apartment {
        Number: number,
        Address: address,
    }
}

func (a *Apartment) Equal(other *Apartment) bool {
    return a.Id == other.Id && a.Number == other.Number && a.Address.Equal(other.Address)
}