// Generated by text/template; DO NOT EDIT
package domain




type Tenant struct {
    Id int
    FirstName string
    LastName string
    SocialSecurityNumber socialSecurityNumber.SocialSecurityNumber
}


func CreateTenant(firstName string, lastName string, socialSecurityNumber socialSecurityNumber.SocialSecurityNumber) Tenant {
    return Tenant {
        FirstName: firstName,
        LastName: lastName,
        SocialSecurityNumber: socialSecurityNumber,
    }
}

func (t *Tenant) Equal(other *Tenant) bool {
    return t.Id == other.Id && t.FirstName == other.FirstName && t.LastName == other.LastName && t.SocialSecurityNumber.Equal(other.SocialSecurityNumber)
}