// Generated by generate.go; do not edit manually
package domain

import "subLease/src/server/socialSecurityNumber"

type Tenant struct {
	Id                   int
	FirstName            string
	LastName             string
	SocialSecurityNumber socialSecurityNumber.SocialSecurityNumber
}

func CreateTenant(firstName string, lastName string, socialSecurityNumber socialSecurityNumber.SocialSecurityNumber) Tenant {
	return Tenant{
		FirstName:            firstName,
		LastName:             lastName,
		SocialSecurityNumber: socialSecurityNumber,
	}
}

func (t *Tenant) Equal(other *Tenant) bool {
	return t.Id == other.Id && t.FirstName == other.FirstName && t.LastName == other.LastName && t.SocialSecurityNumber.Equal(other.SocialSecurityNumber)
}
